apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hwb4e593m-nodejs 
  janus-idp.io/tekton: hwb4e593m-nodejs
  backstage.io/kubernetes-id: hwb4e593m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hwb4e593m-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  